#+TITLE:     Data Structure
#+AUTHOR:    Hao Ruan
#+EMAIL:     ruanhao1116@gmail.com
#+LANGUAGE:  en
#+LINK_HOME: http://www.github.com/ruanhao
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/style.css" />
#+OPTIONS:   H:2 num:nil \n:nil @:t ::t |:t ^:{} _:{} *:t TeX:t LaTeX:t
#+STARTUP:   showall

* 列表


** 切片

- =[:]=   :: 复制
- =[:3]=  :: 前三个
- =[3:]=  :: 第四个到最后
- =[::2]= :: 每两个取一个


** 双向列表

  使用 list 存储数据时，按索引访问元素很快，但是插入和删除元素就很慢了，因为 list 是线性存储，数据量大的时候，插入和删除效率很低。\\
  deque 是为了高效实现插入和删除操作的双向列表，适合用于队列和栈：

  #+BEGIN_SRC python
    from collections import deque
    q = deque(['a', 'b', 'c'])
    q.append('x')
    q.appendleft('y')
    # q: deque(['y', 'a', 'b', 'c', 'x'])
  #+END_SRC


** 应用场景

- 下标循环

  #+BEGIN_SRC python
    for i, value in enumerate(['A', 'B', 'C']):
        print(i, value)
  #+END_SRC



* 生成器

生成器保存的是算法，每次调用 next(g) ，就计算出 g 的下一个元素的值，\\
直到计算到最后一个元素，没有更多的元素时，抛出 StopIteration 异常。

- 函数表示法

  如果一个函数定义中包含 yield 关键字，那么这个函数就不再是一个普通函数，而是一个生成器。\\
  在每次调用 next(g) 的时候执行，遇到 yield 语句返回，再次执行时从上次返回的 yield 语句处继续执行。

  #+BEGIN_SRC python
    def fib(max):
        n, a, b = 0, 0, 1
        while n < max:
            yield b
            a, b = b, a + b
            n = n + 1
        return 'done'
  #+END_SRC


* 字典

dict 的 key 必须是不可变对象

** 有序字典

  #+BEGIN_SRC python
    from collections import OrderedDict

    favorite_languages = OrderedDict()

    favorite_languages['jen']    = 'python'
    favorite_languages['sarah']  = 'c'
    favorite_languages['edward'] = 'ruby'
    favorite_languages['phil']   = 'python'

    for name, language in favorite_languages.items():
        print(name.title() + "'s favorite language is " + language.title() + ".")
  #+END_SRC


** 默认值字典

  使用 dict 时，如果引用的 Key 不存在，就会抛出 KeyError 。如果希望 key 不存在时，返回一个默认值，就可以用 defaultdict。

  #+BEGIN_SRC python
    from collections import defaultdict
    dd = defaultdict(lambda: 'N/A')
    dd['key1'] = 'abc'
    dd['key1']                      # 'abc'
    dd['key2']                      # 'N/A'
  #+END_SRC

  默认值是调用函数返回的，而函数在创建 defaultdict 对象时传入。\\
  除了在 Key 不存在时返回默认值，defaultdict 的其他行为跟 dict 是完全一样的。


** 计数器

  #+BEGIN_SRC python
    from collections import Counter
    c = Counter()
    for ch in 'programming':
        c[ch] = c[ch] + 1

    # c: Counter({'g': 2, 'm': 2, 'r': 2, 'a': 1, 'i': 1, 'o': 1, 'n': 1, 'p': 1})
  #+END_SRC


* 元组

** namedtuple

  namedtuple 是一个函数，它用来创建一个自定义的 tuple 对象，并且规定了 tuple 元素的个数，并可以用属性而不是索引来引用 tuple 的某个元素。\\
  用 namedtuple 可以很方便地定义一种数据类型，它具备 tuple 的不变性，又可以根据属性来引用，使用十分方便。

  #+BEGIN_SRC python
    from collections import namedtuple
    Point = namedtuple('Point', ['x', 'y'])
    p = Point(1, 2)
    p.x                             # 1
    p.y                             # 2
  #+END_SRC